[package]
name = "multi-db-schema-query"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
chrono-tz = "0.10.4"
sqlx = {version = "0.8.6", default-features = false, features = [
    "mysql",
    "runtime-tokio",
    "tls-native-tls",
    "macros",
    "chrono"] }
tokio = { version = "1.48.0", features = [
    "macros",
    "rt",
    "net",
    "io-util"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt", "chrono"] }
